import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Heading, Text, Flex, Box, Container } from "@chakra-ui/react";
import axios from "axios";
import Row from "../components/Row";
import requests from "../utils/apiConfig";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState([]);

  if (loading) return <p>Loading...</p>;

  console.log(process.env.NEXT_PUBLIC_TMDB_API_KEY);

  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Row
        title="Netflix originals"
        fetchUrl={requests.fetchNetflixOriginals}
        isLarge
      />
      <Row title="Trending now" fetchUrl={requests.fetchTrending} />
      <Row title="Top Rated" fetchUrl={requests.fetchTrending} />
      <Row title="Action Movies" fetchUrl={requests.fetchActionMovies} />
      <Row title="Comedy Movies" fetchUrl={requests.fetchComedyMovies} />
      <Row title="Romance Movies" fetchUrl={requests.fetchRomanceMovies} />
    </>
  );
}
